### ISSUE TITLE
Reproduce the training

### ISSUE THREAD

**Issue by roxie62** [bkmi/cnre#1] opened 2023-10-17 17:03 UTC
Dear authors, 

Firstly, I want to thank you for providing the code! They are very helpful for enhancing our understanding our your method.

Second, through reading your Readme file and your provided folders, it seems that I cannot find a complete script to reproduce the training of your method. Especially, I have checked you 'basic algorithm.ipynb'.

At the block of loading the loss function, `l2 = cnre.loss(classifier, theta[:256], x[:256], 2, gamma=1.0, reuse=True)`, the error message on my end is: `NotImplementedError: there is a bug in this computation. refer to https://github.com/mackelab/sbi/blob/main/sbi/inference/snre/snre_c.py`.

And moreover, when running your function `doit(num_atoms=2)', I encountered the error 'module 'cnre.algorithms' has no attribute 'cnre''. And there seems to be no difference between the configuration of your method and the one under the title of 'gillies'.

Given all the issues, could I kindly ask your help?

Thanks!

**Comment by bkmi** [comment] 2023-10-17 17:28
Hello there!

Thank you for your interest. Indeed, I added that exception because I realized there was an error in the computation of the weights (p_0 and p_K from the manuscript). That bug has been fixed in both implementations in [SBI](https://github.com/mackelab/sbi#neural-ratio-estimation-amortized-nre-and-sequential-snre) and [lampe](https://github.com/probabilists/lampe/blob/8eac904491bc8c6cbb66e58a81e5ddfa9c28db71/lampe/inference.py#L202-L256).

I have not had a chance to update the computation within this repository itself. If you're interested in using the method, I would encourage you to view those implementations.

I plan to fix this bug, but my timeframe for that is rather long. I will do it when I am creating the figures for my PhD thesis (i.e. next spring/summer). Reproducing the results exactly shouldn't be too complex by substituting in the implementations I mentioned. In particular the one in the SBI toolkit should be extremely close to the interface I used in this repository.

---

The second bug (in doit) I do not recognize. Do you see the same bug when running the code from `main.py` from the `infinite` folder?

---

Please let me know if you find those other implementations satisfactory. If not, I can try to find some time to investigate these issues further.

Ben

**Comment by bkmi** [comment] 2024-07-04 12:34
solved in the new version. Please enjoy.

**Closed as completed by bkmi** 2024-07-04 12:34 UTC
Labels: bug
